### ISSUE TITLE
timeevent resource

### ISSUE THREAD

**Issue by heming-langrenn** [langrenn-sprint/race-service#24]
url: /timeevents         
   timeevent = {
                    "bib": "414",  # start number
                    "event_id": "KA1",  # event id
                    "race_id": "G11KA1",  # optional input / generated race id
                    "point": "Mål",  # point in race where result where registered
                    "rank": "1",  # optional for interval start
                    "registration_time": "10:01:30.12",  # optional for sprint competition
                    "next_race": "SA1-1",  # optional input / generated, only for sprint competition
                    "status": "OK",  # optional - indicator for quality of event
                    "changelog": "",  # optional - list of dicts { time, user_id, text }. Must be used for all updates.

                }

Status vocabulary:
OK - normal registration, unofficial result
Official - After publishing of official results.
Disputed - when a contestant (or jury) raise a complaint.
Error - other issue, like bib not identified in raceclass. Details to be logged in change_log.

**Comment by stigbd** [comment]
Då har eg laga eit schema for changelog som du kan gjenbruke når du oppdaterer openAPI-spekken:
```
      Changelog:
        type: array
        description: list of changelog entries sorted by timestamp in ascending order.
        items:
          type: object
          properties:
            timestamp:
              type: string
              format: date-time
            userId:
              type: string
            comment:
              type: string
              description: a short description of the reason for the change

```
